<!-- Wrapper-->

<div id="wrapper">

<!-- Nav -->
<nav id="nav"> <a href="/" class="icon fa-home active"><span>Home</span></a> <a href="/?/register" class="icon fa-plus-square"><span>Register</span></a> <a href="/?/manage" class="icon fa-cog "><span>Control</span></a> <a target="_blank" href="https://github.com/typcn/QZone-Cloud-Like" class="icon fa-github"><span>Github</span></a> </nav>

<!-- Main -->
<div id="main">
  <article id="me" class="panel">
    <header>
      <h1>QZone 云点赞</h1>
      <p> <a href="/?/login" class="button" style="font-size:50%;text-decoration: none">登陆</a> <a href="/?/register" class="button" style="font-size:50%;text-decoration: none">注册</a></p>
    </header>
    <a class="pic"> <img src="/default/images/me.jpg" alt="" /> </a> </article>
</div>
