<?php 
if(!$_SESSION['uid']){ header("Location:/?/login"); } 
$url = route_without_rewrite();
$nextmon = date("m") + 1;
$ld = date("d") - 3;
$nx = date("Y")."-".$nextmon."-".$ld;
?>
<!-- Wrapper-->


<div id="wrapper">

<!-- Nav -->
<nav id="nav"> <a href="/" class="icon fa-home "><span>Home</span></a> <a href="/?/register" class="icon fa-plus-square"><span>Register</span></a> <a href="/?/manage" class="icon fa-cog active"><span>Control</span></a> <a target="_blank" href="https://github.com/typcn/QZone-Cloud-Like" class="icon fa-github"><span>Github</span></a> </nav>

<!-- Main -->
<div id="main">
  <?php if($url[2]!="success"){ ?>
  <article id="reg" class="panel" style="width:100%;min-height:280px;">
    <header>
      <h2>设置向导</h2>
      <div id="msg" style="padding-top:2px;color:red"></div>
    </header>
    <div style="display:inline;float:left;width:50%">
      <form action="#">
        <div>
          <div class="row">
            <div class="12u"> 点击<a target="_blank" href="http://pt.3g.qq.com/s?aid=nLogin">此处</a>打开3GQQ页面，在页面上<font color="red">登陆完成之后</font>，将该网页的<font color="red">完整地址</font>复制到下方。 </div>
          </div>
          <div class="row">
            <div class="12u">
              <input id="url" type="text"  placeholder="网址">
            </div>
          </div>
          <div class="row">
            <div class="12u"> 在下方输入您的QQ号，点击保存，系统将自动进行模拟访问测试。 </div>
          </div>
          <div class="row">
            <div class="12u">
              <input id="qq" type="text" placeholder="QQ号">
            </div>
          </div>
          <div class="row">
            <div class="12u"> </div>
          </div>
          <div class="row">
            <div class="12u"> <a onclick="CheckSave()" class="button">保存</a> </div>
          </div>
        </div>
      </form>
    </div>
    <div style="display:inline;float:left;width:40%;margin-left:5%;padding-left:2%;border-left:1px solid;height:100%;">
    	<img src="/default/images/copy.png">
     </div>
  </article>
  <?php }else{?>
  <article id="reg" class="panel" style="width:100%;min-height:280px;">
    <header>
      <h2>设置向导</h2>
      <div id="msg" style="padding-top:2px;color:red"></div>
    </header>
    <div style="display:inline;float:left;width:100%">
      <form action="#">
        <div>
          <div class="row">
            <div class="12u">恭喜您！您已经成功设置了自动点赞！当你的好友发说说时，系统将为您自动点赞！ </div>
          </div>
          <div class="row">
            <div class="12u"> <font color="red"> 请注意：SID每过30天会失效！建议您通过下面的按钮添加提醒，失效时会自动向您的QQ发送消息。</font> </div>
          </div>
          <div class="row">
            <div class="12u"><script type="text/javascript">
   /*
    * 请修改下面js对象的内容以完成定制
    * 内容：请定制为需要提醒用户的内容,
    * 时间：请定制为事件发生的时间，格式为：年-月-日 时:分 
    * advance：请定制为需要提前提醒用户的时间，0为准时提醒
    * url： 请定制为提醒用户访问的url链接
    * icon： 生成的icon的大小，可选值为1，2，3，尺寸分别为90*24，63*24，50*16
    * 注意：如果不使用标准接口，而是按需要自己生成链接地址
    * 请用encodeURIComponent对内容和时间进行编码。
    */ 
var __qqClockShare = {
   content: "您在云点赞平台的SID快要过期啦！快去重新设置吧！(铜芯科技)",
   time: "<?php echo $nx; ?> 9:00",
   advance: 0,
   url: "<?php echo "http://".$_SERVER['SERVER_NAME']; ?>",
   icon: "1_1"
};
document.write('<a href="http://qzs.qq.com/snsapp/app/bee/widget/open.htm#content=' + encodeURIComponent(__qqClockShare.content) +'&time=' + encodeURIComponent(__qqClockShare.time) +'&advance=' + __qqClockShare.advance +'&url=' + encodeURIComponent(__qqClockShare.url) + '" target="_blank"><img src="http://i.gtimg.cn/snsapp/app/bee/widget/img/' + __qqClockShare.icon + '.png" style="border:0px;"/></a>');

</script> </div>
          </div>
        </div>
      </form>
    </div>
    <div style="display:inline;float:left;width:40%;margin-left:5%;padding-left:2%;border-left:1px solid;height:100%;"> </div>
  </article>
  <?php }?>
</div>
<script>
$(document).ready(function() {
	$("body").keydown(function() {
             if (event.keyCode == "13") {//keyCode=13是回车键
                 CheckSave();
             }
	});
});
function CheckSave(){
	var parm = "&u=" + $("#url").val() + "&q=" + $("#qq").val();
	htmlobj=$.ajax({url:"/ajax.php?m=sid" + parm,async:false});
	var rtn = JSON.parse(htmlobj.responseText);
	if(rtn.code==0){
		window.location="/?/manage/success/";	
	}else{
		$("#msg").html(rtn.msg);
	}
}
</script>